sudo: false
dist: trusty
language: rust
# cache: cargo
rust:
  - nightly
    # matrix:
    #   allow_failures:
    #     - rust: nightly
    #   fast_finish: true
install:
  - rustup component add rustfmt-preview
script:
  - cargo test --no-default-features
  - cargo test
  - cargo fmt -- --write-mode check
