name: test

on:
  push:
  pull_request:
  schedule:
    # Weekly at randomly chosen time
    - cron:  '12 14 * * 3'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [nightly]

    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - run: cargo test --all --no-default-features
    - run: cargo test --all
    - name: check format (if rustfmt exists)
      run: |
        if rustup component add rustfmt; then
          cargo fmt --all -- --check
        fi
